version: '3'
services:
  proxy:
    build:
      context: ./infra/
      dockerfile: proxy.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /srv/ca/:/etc/ca/:ro
    depends_on:
      - messstellenbetreiberportal
      - docs
    networks:
      server:
        ipv6_address: 2a01:4f8:1c1c:dfb7:1::ff

  # Infra
  ca:
    build:
      context: ./ca/
      dockerfile: ca.Dockerfile
    volumes:
      - /srv/ca/:/srv/ca/
    networks:
      server:
        ipv6_address: 2a01:4f8:1c1c:dfb7:1::ca
  docs:
    build:
      context: .
      dockerfile: ./infra/swagger.Dockerfile
    networks:
      server:
  
  # Frontend
  messstellenbetreiberportal:
    build:
      context: ./messstellenbetreiberportal/
      dockerfile: webapp.Dockerfile
    depends_on:
      - ca
    volumes:
      - database:/app/backend/db/
    networks:
      server:
        aliases:
          - frontend

  # Meters
  environment:
    build:
      context: ./smartmeter/
      dockerfile: environment.Dockerfile
    networks:
      meters:

  smartmeters:
    build:
      context: ./smartmeter/
      dockerfile: smartmeter.Dockerfile
    networks:
      meters:
    depends_on:
      - environment
      - ca
    deploy:
      replicas: 25

volumes:
  database:

networks:
  server:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 2a01:4f8:1c1c:dfb7:1::/80
        gateway: 2a01:4f8:1c1c:dfb7:1::1
  meters:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 2a01:4f8:1c1c:dfb7:2::/80
        gateway: 2a01:4f8:1c1c:dfb7:2::1
