version: '3'
name: meters
services:
  environment:
    build:
      context: ./smartmeter/
      dockerfile: environment.Dockerfile
    networks:
      meters:

  smartmeters:
    build:
      context: ./smartmeter/
      dockerfile: smartmeter.Dockerfile
    networks:
      meters:
    depends_on:
      - environment
    deploy:
      replicas: 25

networks:
  meters:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 2a01:4f8:1c1c:dfb7:2::/80
        gateway: 2a01:4f8:1c1c:dfb7:2::1