---
- hosts: all
  vars:
    hetzner_ipv6_net: "2a01:4f8:1c1c:dfb7::"
    userliste:
      - username: "jle"
        sshkey: "https://raw.githubusercontent.com/JM-Lemmi/JM-Lemmi/main/authorized_keys"
      - username: "bwe"
        sshkey: "https://raw.githubusercontent.com/Petzys/Petzys/main/authorized_keys"
      - username: "hpl"
        sshkey: "https://cdn.discordapp.com/attachments/980906916404416572/1177941842076127292/id_ed25519.pub?ex=657456d4&is=6561e1d4&hm=27ab65281a24da24ae3aa3ff816644ac6c95178ca505fe3e3c6b7faf3fb458db&"


  tasks:
    ### User Setup ###
    - name: "Add Root SSH Authorized Keys for jle"
      ansible.posix.authorized_key:
        user: "root"
        state: present
        key: "{{ item }}"
      with_items:
        - "https://raw.githubusercontent.com/JM-Lemmi/JM-Lemmi/main/authorized_keys"     
    
    - name: "Ensure sudo is installed"
      package:
        name: "sudo"
        state: "latest"
    - name: "Create user accounts"
      user:
        shell: "/bin/bash"
        name: "{{ item.username }}"
        groups: "sudo,docker"
      with_items: "{{ userliste }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ item.sshkey | default('') }}"
        # the default makes the line fail, but not fatal. maybe there is a nicer solution.
      ignore_errors: True
      with_items: "{{ userliste }}"
    
    - name: "Set DNS-Servers for NAT64"
      # Needed for Github and other Legacy Services
      ansible.builtin.copy:
        dest: "/etc/resolv.conf"
        content: |
          nameserver 2a01:4f9:c010:3f02::1
          nameserver 2a01:4f8:c2c:123f::1
          nameserver 2a00:1098:2c::1
    
    ### Updates ###
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    ### Docker ###
    - name: "[Docker Setup] Install Dependencies"
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3
          - pipx
          - python3-docker
        state: present
        update_cache: true
    - name: "[Docker Setup] Docker Repo-GPG"
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: "[Docker Setup] Docker Repository"
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
    - name: "[Docker Setup] Install Docker"
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true
    
    - name: "[Docker Setup] Enable IPv4"
      ansible.builtin.copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
            "ipv6": true,
            "fixed-cidr-v6": "2a01:4f8:1c1c:dfb7:dddd::/80"
          }
      notify:
        - restart docker

    ### Get Project Data ###
    - name: "Install Package dependencies"
      ansible.builtin.apt:
        name:
          - git
        state: present
    
    - name: "Clone Project"
      ansible.builtin.git:
        repo: "https://github.com/TINF21CS1/kilowatt_kojote"
        dest: "/opt/kilowatt_kojote"
        update: yes
        version: main
  
  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
