name: Build Docker Containers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        file:
          - context: ./ca
            file: ./ca/ca.Dockerfile
          - context: ./infra
            file: ./infra/proxy.Dockerfile
          - context: .
            file: ./infra/swagger.Dockerfile
          - context: ./messstellenbetreiberportal
            file: ./messstellenbetreiberportal/webapp.Dockerfile
          - context: ./smartmeter
            file: ./smartmeter/smartmeter.Dockerfile
          - context: ./smartmeter
            file: ./smartmeter/environment.Dockerfile
          - context: ./infra
            file: ./infra/backup.Dockerfile
          - context: .
            file: ./infra/db-mgmt.Dockerfile

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.file.context }}
          file: ${{ matrix.file.file }}
          platforms: ${{ matrix.platform }}